### ISSUE TITLE
Kibana 5.6.2 help on request index

### ISSUE THREAD

**Issue by hcountou** [nyurik/kibana-vega-vis#26]
Hello,

great job, you help us a lot with that plugin integration.
But we still have a question about how to properly configure the json in order to reach an elasticsearch index for drawing a simple scatter plot. We are stuck can you help us ?
From this example
![vega editor 1](https://user-images.githubusercontent.com/17201656/31556700-56717d58-b046-11e7-9525-972bc35de699.png)

We manage to copy and make it run
![vega editor 2](https://user-images.githubusercontent.com/17201656/31556699-5653779a-b046-11e7-94c6-14aee128fc6f.png)

But even with your indication on github, we are stuck.
![vega editor 3](https://user-images.githubusercontent.com/17201656/31556697-5603df64-b046-11e7-98fc-0c2f257e5c84.png)

Do you have any clue ?

Thank you in advance for any kind of help.

Best regards.

Hector

**Comment by hcountou** [comment]
Index seems to be found, but i'm not sure of the other parameters. I suppose i have to change them in order to match the scatter plot example (and not the histogram one).

Thanks.

**Comment by nyurik** [comment]
@hcountou in order to help, I need to have a sample of your data. Please upload it in the structure you have, plus provide a query if you have one to get just the data you need from ES.

**Comment by hcountou** [comment]
Hello,

thank you for the quick answer.

Those data are not sensible. So here they are.
[Data_test.txt](https://github.com/nyurik/kibana-vega-vis/files/1386755/Data_test.txt)

We wanted a simple scatter plot nicer than the one we can obtain in kibana.
- The number of "yes" corresponding to the values (in the yes column)
- For each reco listed
- And this for each type of dimension.

We generate our index with logstash. I don't know i you want our logstash conf file ?

We added an example also.

Thank you again for your help.

Best regards.

**Comment by hcountou** [comment]
![stopp_start_ dashboard_kibana](https://user-images.githubusercontent.com/17201656/31604053-6be78af6-b262-11e7-8dd9-74d6a51ca5f3.png)

**Comment by nyurik** [comment]
I recreated your data using these two commands from the Kibana dev console:
https://gist.github.com/nyurik/78442ad6a4218157114594c67b58272b

With that, I am able to do a very dumb graph (it pulls a lot of points from the server and does local aggregation):
https://gist.github.com/nyurik/85f8a53199f69c28d3585b1d936b2459

The graph was adapted from this Vega example:
https://vega.github.io/vega/examples/scatter-plot/

The reason I couldn't use Vega Lite was due to a bug there, filed at
https://github.com/vega/vega-lite/issues/3137

If you have a huge amount of data, we will need to think of how best to aggregate it somehow, and then the graph might change.

**Comment by nyurik** [comment]
@hcountou [v0.4.0](https://github.com/nyurik/kibana-vega-vis/releases/tag/v0.4.0) has been published, fixing the above issues.  Let me know if there are any other issues with it.
