### ISSUE TITLE
Vega-lite 2.3.0

### ISSUE THREAD

**Issue by chuski92** [nyurik/kibana-vega-vis#51]
Hello!
Are you planning to continue updating the plugin or as it is included in kibana it will be released with newer versions of it?

I have some issues related to the version of vega-lite, that are working with their editor but not with kibana. It is possible to upgrade the version of vega-lite of the plugin without having to update all? Something like drag and drop the vega-lite new version on the same plugin folder?

Also, thank you very much for creating that plugin that makes my life happier!

**Comment by nyurik** [comment]
Kibana 6.3 will ship with the latest Vega & VL libs -- https://github.com/elastic/kibana/pull/17314  
I do plan to release updates for a bit longer, in my spare time, but it is becoming increasingly more difficult because Kibana's API keeps changing, and it is fairly difficult to support multiple Kibana versions in the same code base.

**Comment by nyurik** [comment]
Also, I just released another version for 6.0 and 6.1 https://github.com/nyurik/kibana-vega-vis/releases/tag/v1.1.2

**Comment by chuski92** [comment]
Thank you @nyurik!
