### ISSUE TITLE
Need this plugin for Kibana 6.2.x

### ISSUE THREAD

**Issue by chintanrp** [nyurik/kibana-vega-vis#54]
Can you please help to get build to support Kibana 6.2.x? I really need after our recently upgrade from 5.x to 6.2.x upgrade on elasticsearch cluster.

**Comment by nyurik** [comment]
@chintan-29 are you using interactive maps from Vega?  If not, the built-in Vega has the same functionality.

**Comment by chintanrp** [comment]
Yes, I have one visualization for interactive map.
So, this vega version will work with ES 6.2 without any changes? Because your builds are only till 6.1.x.

**Comment by nyurik** [comment]
@chintan-29 everything except interactive graphs on top of zoomable/pannable base map will work. You might have to copy the the vega spec from the plugin to the built-in version, but otherwise should be identical. It is mostly the same code.  The map support has been merged for Kibana 6.3, so you should have that too once it ships.  I still plan to release 6.2, as soon as I get some time.

**Comment by chintanrp** [comment]
Thanks...
