### ISSUE TITLE
Getting errors when refreshing visual

### ISSUE THREAD

**Issue by thekofimensah** [nyurik/kibana-vega-vis#59]
Kibana 6.2.2 (updated plugin)

I've been getting this error when my vega visual reloads either through a resize (which causes a reload of the visual) or sending a query via filters or on the search bar and pressing search once or twice in a row. 

When I first load the dash, I can see the visual perfectly and everything works. If I type something into the search bar and press search more than once for the same filter, then the visual at first disappears and then after that I get the error `Cannot read property 'value' of undefined`. This happens in both dashboard and visualization view. When looking at the vega.debug when the error appears, the data doesn't seem to be loaded.. as if the query doesn't succeed and so I can't see the data. Which makes sense for the error that I'm getting. I've checked and this doesn't happen with the default vega visual so I'm not sure why this is happening with mine. I have a few different transforms that happen: `formula`, `fold`,`nest`,`treemap` which is maybe the cause.

Let me know if you want more information

**Comment by nyurik** [comment]
@seanziee i have also observed it a few times, and I suspect this is due to how `formula` transform works - if you override an existing field.  For example, if your data has `{ field: { subfield: 10 }}`, and your formula transform is like this:  `{type: 'formula', expr: 'datum.field.subfield', as: 'field'}` (basically overriding the initial value of `field` with a new one), it seems this error sometimes happens. Could you try to change the "as" parameter to something else, e.g. `field_new`, and use that everywhere else to see how it works?  Thanks!

P.S. this could also be due to https://github.com/vega/vega/issues/1239

**Comment by thekofimensah** [comment]
Wow, this was exactly the issue. Amazing! Just got it fixed by changing it so the `field` values are slightly different. Thanks!

**Comment by nyurik** [comment]
@domoritz remember i was mentioning some issue with formula processing
