### ISSUE TITLE
Error messages must be dismissable

### ISSUE THREAD

**Issue by nplatis** [nyurik/kibana-vega-vis#60]
Error messages appear as red stripes (alerts) over the graph area, but they cannot go away. They should probably have an "X" button so that they can be dismissed.

**Comment by nyurik** [comment]
@nplatis my thinking was that the errors and warnings only occur during development, and restarting the graph (ctrl+Enter) would reset them.  Usually if there is an error, Vega tends to spew a lot of them to the screen, and closing them one by one is useless. Of course I could use Kibana's standard error bar at the very top, but doing that causes a graph resize, and most errors tend to show up during graph re-evaluation, further compounding the problem. Could you describe your usecase to keep the erorrs?

**Comment by nplatis** [comment]
@nyurik The way to show the error messages is fine, since the red bars are transparent. 

Of course I would not want to "keep" any errors :)
My case was that I had an error "always on", but it just seems that it appears right when the visualization is run, so it always appears again after re-running it (without disappearing even momentarily).

However, I may have another case: when messages fill the screen, next messages do not appear, ie. messages do not seem to "scroll down". So the ability to dismiss some of them would show me the next ones.

But this is probably a border case, so if it is too much trouble to implement this, just skip it.

**Comment by nyurik** [comment]
@nplatis wrt multiple messages - i almost always find just the first message as the really important one. Vega frequently fails multiple times in different ways due to the very first error, so fixing that first error fixes all subsequent ones. Hiding the first error wouldn't really help, nor would showing multiple errors beyond the first screen.
As for the first error - unless you fix it, there is really no point in the graph, so its the error that's the most important, not the graph underneath (which you can mostly see anyway). So for now I will not resolve it as I see very little value in it, but in theory it could be made to appear at the top as standard Kibana errors with an additional Vega configuration.
